#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/crictl
- name: Set crictl version v1.37.0
  ansible.builtin.set_fact:
    crictl_version: "v1.37.0"

- name: Download crictl
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl_version }}/crictl-{{ crictl_version }}-linux-amd64.tar.gz
    checksum: sha256:https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl_version }}/crictl-{{ crictl_version }}-linux-amd64.tar.gz.sha256
    dest: /opt/crictl-{{ crictl_version }}-linux-amd64.tar.gz

- name: Extract archive
  ansible.builtin.unarchive:
    src: /opt/crictl-{{ crictl_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes